# Generated by Django 2.2.5 on 2019-09-24 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimize', '0002_auto_20190921_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='close_price',
            field=models.FloatField(),
        ),
    ]
