# Generated by Django 2.2.5 on 2019-09-27 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimize', '0003_auto_20190924_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='symbol',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
